In [1]:
from RDMM.generate_correlation import *

In [2]:
generate_cov_parameters(5)

array([[ 6.18017047,  0.17570553,  0.1193527 ,  0.14205115, -0.25302322],
       [ 0.17570553,  5.44400363, -0.37135996, -0.6212279 ,  0.8133129 ],
       [ 0.1193527 , -0.37135996,  6.39380018,  0.02474831,  0.05096295],
       [ 0.14205115, -0.6212279 ,  0.02474831,  6.81282028,  0.11400783],
       [-0.25302322,  0.8133129 ,  0.05096295,  0.11400783,  5.47424879]])

In [3]:
import numpy as np

In [4]:
def generate_cov_parameters(d, d_sigma=(0.1, 10)):
    q, _ = np.linalg.qr(np.random.rand(d,d))
    Lambda = np.diag(np.random.uniform(*d_sigma, size=d))
    print(Lambda)
    arr=q @ Lambda @ q.T
    return arr

In [5]:
np.linalg.eigh(generate_cov_parameters(5))

[[3.25434257 0.         0.         0.         0.        ]
 [0.         0.72802631 0.         0.         0.        ]
 [0.         0.         6.11110487 0.         0.        ]
 [0.         0.         0.         0.24615332 0.        ]
 [0.         0.         0.         0.         0.84548337]]


(array([0.24615332, 0.72802631, 0.84548337, 3.25434257, 6.11110487]),
 array([[-0.70833802, -0.19735129,  0.08425441,  0.24719896, -0.62538275],
        [ 0.16901114,  0.59618058, -0.41396787,  0.64156384, -0.18174266],
        [-0.3758568 , -0.35174468, -0.25728404,  0.45278659,  0.68102612],
        [ 0.48273779, -0.67860776, -0.41893377,  0.13839988, -0.33435864],
        [ 0.30885008, -0.14624764,  0.76146649,  0.55056179,  0.01654526]]))